### ISSUE TITLE
Application should not fail if no hadoop binaries are on the classpath

### ISSUE THREAD

**Issue by kevinwallimann** [AbsaOSS/hyperdrive-trigger#726]
## Description
Currently, the application fails with the following error, when no hadoop-binaries are no the classpath

```
	Caused by: java.lang.IllegalStateException: Failed to introspect Class [za.co.absa.hyperdrive.trigger.api.rest.services.HyperdriveOffsetComparisonServiceImpl] from ClassLoader [ParallelWebappClassLoader
  context: hyperdrive_trigger
  delegate: false
----------> Parent Classloader:
java.net.URLClassLoader@1a6c5a9e
]
		at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:485)
		at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:321)
		at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:267)
		... 101 more
	Caused by: java.lang.NoClassDefFoundError: org/apache/hadoop/security/UserGroupInformation
		at java.lang.Class.getDeclaredMethods0(Native Method)
		at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
		at java.lang.Class.getDeclaredMethods(Class.java:1975)
		at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:467)
		... 103 more
	Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.security.UserGroupInformation
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1363)
		at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1186)
		... 107 more
```

This happens, even if `scheduler.executors.enableHyperdriveExecutor` is set to false.

## Expected behaviour
If `scheduler.executors.enableHyperdriveExecutor` is set to false, no such exception should be thrown, as the functionality is disabled anyway and hadoop-binaries are not needed in that case.

**Comment by kevinwallimann** [comment]
Closed by #728
